//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework5.SolarRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="inputData", Namespace="http://schemas.datacontract.org/2004/07/SolarEnergyEstimation")]
    [System.SerializableAttribute()]
    public partial class inputData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string capacityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lossesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string zipcodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string capacity {
            get {
                return this.capacityField;
            }
            set {
                if ((object.ReferenceEquals(this.capacityField, value) != true)) {
                    this.capacityField = value;
                    this.RaisePropertyChanged("capacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string losses {
            get {
                return this.lossesField;
            }
            set {
                if ((object.ReferenceEquals(this.lossesField, value) != true)) {
                    this.lossesField = value;
                    this.RaisePropertyChanged("losses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string zipcode {
            get {
                return this.zipcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.zipcodeField, value) != true)) {
                    this.zipcodeField = value;
                    this.RaisePropertyChanged("zipcode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolarEnergyInformation", Namespace="http://schemas.datacontract.org/2004/07/SolarEnergyEstimation")]
    [System.SerializableAttribute()]
    public partial class SolarEnergyInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string annualACOutputField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string annualDCOutputField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string annualSolarRadOutputField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] monthlyACOutputField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] monthlyDCOutputField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] monthlySolarRadOutputField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string testStrField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string annualACOutput {
            get {
                return this.annualACOutputField;
            }
            set {
                if ((object.ReferenceEquals(this.annualACOutputField, value) != true)) {
                    this.annualACOutputField = value;
                    this.RaisePropertyChanged("annualACOutput");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string annualDCOutput {
            get {
                return this.annualDCOutputField;
            }
            set {
                if ((object.ReferenceEquals(this.annualDCOutputField, value) != true)) {
                    this.annualDCOutputField = value;
                    this.RaisePropertyChanged("annualDCOutput");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string annualSolarRadOutput {
            get {
                return this.annualSolarRadOutputField;
            }
            set {
                if ((object.ReferenceEquals(this.annualSolarRadOutputField, value) != true)) {
                    this.annualSolarRadOutputField = value;
                    this.RaisePropertyChanged("annualSolarRadOutput");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] monthlyACOutput {
            get {
                return this.monthlyACOutputField;
            }
            set {
                if ((object.ReferenceEquals(this.monthlyACOutputField, value) != true)) {
                    this.monthlyACOutputField = value;
                    this.RaisePropertyChanged("monthlyACOutput");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] monthlyDCOutput {
            get {
                return this.monthlyDCOutputField;
            }
            set {
                if ((object.ReferenceEquals(this.monthlyDCOutputField, value) != true)) {
                    this.monthlyDCOutputField = value;
                    this.RaisePropertyChanged("monthlyDCOutput");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] monthlySolarRadOutput {
            get {
                return this.monthlySolarRadOutputField;
            }
            set {
                if ((object.ReferenceEquals(this.monthlySolarRadOutputField, value) != true)) {
                    this.monthlySolarRadOutputField = value;
                    this.RaisePropertyChanged("monthlySolarRadOutput");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string testStr {
            get {
                return this.testStrField;
            }
            set {
                if ((object.ReferenceEquals(this.testStrField, value) != true)) {
                    this.testStrField = value;
                    this.RaisePropertyChanged("testStr");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SolarRef.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getSolarIntensity", ReplyAction="http://tempuri.org/IService1/getSolarIntensityResponse")]
        Homework5.SolarRef.SolarEnergyInformation getSolarIntensity(Homework5.SolarRef.inputData inData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getSolarIntensity", ReplyAction="http://tempuri.org/IService1/getSolarIntensityResponse")]
        System.Threading.Tasks.Task<Homework5.SolarRef.SolarEnergyInformation> getSolarIntensityAsync(Homework5.SolarRef.inputData inData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Homework5.SolarRef.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Homework5.SolarRef.IService1>, Homework5.SolarRef.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Homework5.SolarRef.SolarEnergyInformation getSolarIntensity(Homework5.SolarRef.inputData inData) {
            return base.Channel.getSolarIntensity(inData);
        }
        
        public System.Threading.Tasks.Task<Homework5.SolarRef.SolarEnergyInformation> getSolarIntensityAsync(Homework5.SolarRef.inputData inData) {
            return base.Channel.getSolarIntensityAsync(inData);
        }
    }
}
